title: 专注提升技术，完善知识体系
description: 技术体系,开源技术博客,IT 博客,java技术,spring开源技术,dubbo分布式架构,maven工具,Kubernetes,docker
author: 专注提升技术
logo: http://www.mixfate.com/static/img/avatar.png
github: https://github.com/
about: java,spring,kubernetes
disqus_shortname: mixfate
google_analytics: UB-72862926-2
urls:
    - text: 首页
      url: /
      icon: fa-home
      layout: post
    - text: 分类
      url: /category/java
      icon: fa-desktop
    - text: 关于
      url: /about/
      icon: fa-comments
      
social:
    - icon: fa-facebook
      link: ''
    - icon: fa-skype
      link: ''
    - icon: fa-twitter
      link: ''
    - icon: fa-linkedin
      link: ''
    - icon: fa-stack-exchange
      link: ''

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "http://www.mixfate.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist